server:
  port: 9000
mybatis:
  mapper-locations: mapper/*Mapper.xml
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: gateway-service
  datasource:
    url: jdbc:mysql:///logistics
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    tomcat:
      max-idle: 100
      min-idle: 10
      max-active: 100
      max-wait: 10000
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
  redis:
    host: localhost
    port: 6379
    database: 0
    jedis:
      pool:
        max-active: 1000
        max-idle: 100
        min-idle: 10
        max-wait: 1000
feign:
  hystrix:
    enabled: true
zuul:
  routes:
    goods-service: /gateway/goods/**
    order-service: /gateway/order/**
    gateway-service: /gateway/lj/**
    shiro-service : /gateway/shiro/**


  ignored-patterns: /*-service/**
  sensitive-headers: Access-Control-Allow-Origin,Access-Control-Allow-Methods




